version: '3.1'

services: 
  # Add this top-level entry
  redis:
    image: redis
    # container_name: cache
    ports:
      - "6379:6379"
  # APP API
  smart-brain-api: 
    container_name: backend
    # image: node: :10.10.0
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    # restart: always
    environment: 
      # - COMPOSE_CONVERT_WINDOWS_PATHS=1 # On Docker Toolbox Solution
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: 12345
      # POSTGRES_DB: dbsb
      # POSTGRES_HOST: postgres # localhost
      # OR
      # POSTGRES_URI: postgres://postgres:12345@localhost:5432/dbsb
      POSTGRES_URI: postgres://postgres:12345@postgres:5432/dbsb
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports: 
      - "3001:3001"
    # expose: 
    #   - 3000
    volumes: 
      - ./:/usr/src/smart-brain-api

  # PostgreSQL
  postgres:
    # container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: dbsb
      POSTGRES_HOST: postgres # localhost
    # image: postgres
    build: ./postgres
    ports:
      - "5432:5432"
    
