BEGIN TRANSACTION;

CREATE TABLE tbusers (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100),
	email TEXT UNIQUE NOT NULL,
	entries BIGINT DEFAULT 0,
	age INT,
	pet TEXT,
	joined TIMESTAMP NOT NULL
);

COMMIT;